Use enum variants in the SPI driver
riscv-rust/e310x-hal pull request #39
Opened 2021-08-01 11:38 UTC by Disasm

2021-08-01 15:43 UTC, almindor requested changes
one comment nit

2021-08-01 15:43 UTC, almindor commented on src/spi.rs
>      /// Set AUTO CS mode to per-frame operation
Set HOLD CS mode

2021-08-01 15:46 UTC, Disasm commented on src/spi.rs
>      /// Set AUTO CS mode to per-frame operation
Oops, thanks!

2021-08-01 16:09 UTC, almindor approved these changes

2021-08-02 06:21 UTC, almindor approved these changes

2021-08-02 20:00 UTC, merged