Add PWM driver
riscv-rust/e310x-hal pull request #47
Opened 2022-09-29 21:00 UTC by timbz

Basic PWM implementation. Tested on Hifive1 rev 1. Should also work on rev B.

I am new to Rust and embedded hal. Let me know if this is the correct way of doing things.
References:

- [serial](https://github.com/riscv-rust/e310x-hal/blob/master/src/serial.rs) and [spi](https://github.com/riscv-rust/e310x-hal/blob/master/src/spi.rs) driver
- [SiFive manual](https://sifive.cdn.prismic.io/sifive/4faf3e34-4a42-4c2f-be9e-c77baa4928c7_fe310-g000-manual-v3p2.pdf) 
- [SiFive SDK](https://github.com/sifive/freedom-metal/blob/master/src/drivers/sifive_pwm0.c)
- [Arduino `wiring_analog`](https://github.com/sifive/cinco/blob/master/hardware/freedom_e/cores/arduino/wiring_analog.c)
- https://github.com/riscv-rust/e310x-hal/pull/32 as a reference.

Sample code that fades the green led:
```rust
    let mut pwm1 = Pwm::new(p.PWM1);
    pwm1.set_period(u16::MAX);
    let pwm1_1 = Channel::from(pin!(pins, dig3).into_iof1());

    type Duty = u16;
    const DELAY: u32 = 30;
    const INCREMENT: Duty = Duty::MAX / 51;
    let mut duty: Duty = 0;
    let mut increment = true;

    loop {
        if increment {
            duty = duty.saturating_add(INCREMENT);
        } else {
            duty = duty.saturating_sub(INCREMENT);
        }
        if duty == 0 || duty == Duty::MAX {
            increment = !increment;
        }
        pwm1.set_duty(pwm1_1, duty);
        sleep.delay_ms(DELAY);
    }
```

2022-09-29 21:17 UTC, almindor commented
@timbz looking great thanks! Please fix formatting (just run `cargo fmt` over and push that). I'll do a deeper dive over the weekend or so.

2022-09-30 18:38 UTC, timbz commented
> @timbz looking great thanks! Please fix formatting (just run `cargo fmt` over and push that). I'll do a deeper dive over the weekend or so.

done

2022-10-02 22:05 UTC, almindor approved these changes

2022-10-02 22:06 UTC, almindor commented
> > @timbz looking great thanks! Please fix formatting (just run `cargo fmt` over and push that). I'll do a deeper dive over the weekend or so.
> 
> done

Sorry, one more nit, it needs a changelog entry (unrelased section). All good otherwise I'll merge as soon as that's done.

2022-10-02 22:06 UTC, almindor requested changes
needs a CHANGELOG entry

2022-10-03 13:21 UTC, timbz commented
> needs a CHANGELOG entry

done

2022-10-03 15:03 UTC, almindor approved these changes

2022-10-03 15:03 UTC, merged